name: My First Action

on:
  push:

jobs:
  hello-hi:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello from github
        run: echo "Hello from GitHub Actions!"

      - name: Show files
        run: ls -la